import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { zipSync, strToU8, unzipSync } from 'fflate';
import { parseTotvsZip, parseCsv, selectTotvsPayload } from '../server/services/totvs-import.service.mjs';

const zipPath = process.argv[2];
if (!zipPath) throw new Error('Informe o ZIP de referência.');
const buffer = await readFile(zipPath);
const actual = parseTotvsZip(buffer, '2026-08');
assert.equal(actual.inventory.length, 31);
const stored = selectTotvsPayload(actual);
assert.deepEqual(Object.keys(stored).sort(), ['lists','reportPeriod','sourceUpdatedAt']);
assert.deepEqual(Object.keys(stored.lists), ['categories']);
assert.equal(stored.lists.categories.length, 3);
assert.equal(stored.lists.categories.reduce((sum, row) => sum + row.count, 0), 97);
assert.equal(JSON.stringify(stored).includes('MGI'), false);
assert.deepEqual(actual.series.find(row => row.period === '2026-08'), { period: '2026-08', opened: 195, closed: 201, inSla: 180, outSla: 17, tms: 24.85, satisfaction: 100, abstention: 98.51 });
assert.equal(actual.series.some(row => row.period > '2026-09'), false, 'Previsões não são aberturas reais');
assert.equal(actual.lists.backlogCompany.reduce((sum,row) => sum + row.count, 0), 66);
assert.equal(actual.lists.backlogGroup.reduce((sum,row) => sum + row.count, 0), 54);
assert.ok(actual.warnings.some(row => row.includes('Backlog divergente')));
assert.ok(actual.warnings.some(row => row.includes('79.7')));
assert.deepEqual(parseCsv('a,b\r\n1,"nome, sobrenome"\r\n2,"linha\ncom ""aspas"""'), [['a','b'],['1','nome, sobrenome'],['2','linha\ncom "aspas"']]);
assert.throws(() => parseCsv('a,"sem fechamento'));
assert.throws(() => parseTotvsZip(buffer, '2026-13'));
assert.throws(() => parseTotvsZip(Buffer.from('invalid'), '2026-08'));
assert.throws(() => parseTotvsZip(zipSync({'outro.csv': strToU8('a,b\n1,2')}), '2026-08'));
const files = unzipSync(buffer);
const satisfaction = Object.keys(files).find(name => name.startsWith('Satisfação_Global'));
delete files[satisfaction];
const missing = parseTotvsZip(zipSync(files), '2026-08');
assert.equal(missing.series.find(row => row.period === '2026-08').satisfaction, undefined, 'Ausência não vira zero');
assert.ok(missing.warnings.some(row => row.includes('Arquivos ausentes')));
const duplicate = { ...files, ['duplicado/' + Object.keys(files)[0]]: files[Object.keys(files)[0]] };
assert.throws(() => parseTotvsZip(zipSync(duplicate), '2026-08'), /duplicado/i);
const wrongPeriod = parseTotvsZip(buffer, '2026-07');
assert.ok(wrongPeriod.warnings.some(row => row.includes('Confira o período')));
console.log('TOTVs: referência real, previsões, divergências, período incorreto, CSV com aspas, ZIP inválido, duplicatas e ausência de dados verificados.');
